### PR TITLE
Fix HunspellRuleTest on Windows

### LINKED ISSUE #2202: Maven Clean Test Failure on language-fr
Attempting to run the command 'mvn clean test' results in the following error and log:

[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:29 min
[INFO] Finished at: 2019-12-02T08:43:41Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.0:test (default-test) on project language-fr: There are test failures.
[ERROR]
[ERROR] Please refer to C:\Users\Jack\Downloads\languagetool\languagetool-language-modules\fr\target\surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date]-jvmRun[N].dump, [date].dumpstream and [date]-jvmRun[N].dumpstream.
[ERROR] -> [Help 1]
[ERROR]

-------------------------------------------------------------------------------
Test set: org.languagetool.rules.spelling.hunspell.HunspellRuleTest
-------------------------------------------------------------------------------
Tests run: 2, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 3.094 s <<< FAILURE! - in org.languagetool.rules.spelling.hunspell.HunspellRuleTest
testRuleWithFrench(org.languagetool.rules.spelling.hunspell.HunspellRuleTest)  Time elapsed: 1.815 s  <<< FAILURE!
java.lang.AssertionError: Got != 0 matches for: Aujourd’hui et jusqu’à demain.: [HUNSPELL_RULE:0-7:Faute de frappe possible trouvée, HUNSPELL_RULE:8-11:Faute de frappe possible trouvée, HUNSPELL_RULE:15-20:Faute de frappe possible trouvée]
	at org.junit.Assert.fail(Assert.java:88)
	at org.languagetool.rules.spelling.hunspell.HunspellRuleTest.test(HunspellRuleTest.java:63)
	at org.languagetool.rules.spelling.hunspell.HunspellRuleTest.testRuleWithFrench(HunspellRuleTest.java:54)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:365)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:273)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:159)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:383)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:344)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:125)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:417)

### PR DESCRIPTION
**Pull request by asashour**
Fixes #2202

The reason was: Scanner behavior is different with maven in Windows, and `Scanner(File)` had been replaced globally by `Files.readAllLines`.

However, there are still failed tests on windows, but would be handled separately.

### CODE REVIEW

File: languagetool-dev/src/main/java/org/languagetool/dev/httpchecker/HttpApiSentenceChecker.java [hunk 1]
```diff
@@ -80,15 +80,8 @@ private String formatDuration(Duration duration) {
...
-    int count = 0;
-    try (Scanner sc = new Scanner(input)) {
-      while (sc.hasNextLine()) {
-        sc.nextLine();
-        count++;
-      }
-    }
-    return count;
+  private int countLines(File input) throws IOException {
+    return Files.readAllLines(input.toPath()).size();
```
Comment (danielnaber) [inline languagetool-dev/src/main/java/org/languagetool/dev/httpchecker/HttpApiSentenceChecker.java:84]: I'm not sure if this is a good idea, the input file could be very large and would be loaded into memory this way (the same is true for other cases in HttpApiSentenceChecler)...

Comment (asashour) [reply languagetool-dev/src/main/java/org/languagetool/dev/httpchecker/HttpApiSentenceChecker.java]: You are definitely right, this approach doesn't work for large files.

It has been changed, please let me know if other places also need lines to be read one-by-one.

**Comment by asashour** [comment]
Please also note, Travis seems to hang at a previous build.

File: languagetool-dev/src/main/java/org/languagetool/dev/bigdata/TextIndexCreator.java [hunk 2]
```diff
@@ -56,16 +57,13 @@ private void index(File outputDir, String[] inputFiles) throws IOException {
...
-      while (scanner.hasNextLine()) {
-        String line = scanner.nextLine();
-        Document doc = new Document();
-        doc.add(new TextField(Lucene.FIELD_NAME, line, Field.Store.YES));
-        doc.add(new TextField(Lucene.FIELD_NAME_LOWERCASE, line.toLowerCase(), Field.Store.YES));
-        indexWriter.addDocument(doc);
-        if (++lineCount % 10_000 == 0) {
-          System.out.println(lineCount + "...");
-        }
+    for (String line : Files.readAllLines(Paths.get(inputFile))) {
```
Comment (danielnaber) [inline languagetool-dev/src/main/java/org/languagetool/dev/bigdata/TextIndexCreator.java:60]: This should also use scanner to avoid reading everything into RAM.

File: languagetool-dev/src/main/java/org/languagetool/dev/diff/LightRuleMatchParser.java [hunk 3]
```diff
@@ -54,18 +55,17 @@
     ObjectMapper mapper = new ObjectMapper();
     List<LightRuleMatch> ruleMatches = new ArrayList<>();
     int lineCount = 1;
-    try (Scanner scanner = new Scanner(inputFile)) {
-      while (scanner.hasNextLine()) {
-        String line = scanner.nextLine();
+    for (String line : Files.readAllLines(inputFile.toPath())) {
```
Comment (danielnaber) [inline languagetool-dev/src/main/java/org/languagetool/dev/diff/LightRuleMatchParser.java:58]: This should also use scanner to avoid reading everything into RAM.

Comment (asashour) [reply languagetool-dev/src/main/java/org/languagetool/dev/diff/LightRuleMatchParser.java]: Done, and I removed the try/catch, because no exception is thrown from the enclosed methods.
